project:
  type: website
  output-dir: docs

website:
  title: "CMPSC101 Fall 2025 :: DataStructures"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
      - href: utils/interactivePython.qmd
        text: Python Interactive
      - href: lessons/lessons.qmd
        text: Lessons Playground
      # - href: syllabus/syllabus.qmd
        # text: Syllabus

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



